### PR TITLE
README fixup

### PR DESCRIPTION
**Pull request by argent-smith**
... and would you @carlosbrando please release the recent changes: I'd like to announce/use the gem in all my FreeBSD related projects.

Thanks for a great tool!

### CODE REVIEW

**Comment by carlosbrando** [comment]
All your tests are passing?

**Comment by argent-smith** [comment]
No but.. those aren't passing which I took from Linux code (Linux test failed as well to start with). Here's what I see:

```
Finished tests in 0.114236s, 358.9070 tests/s, 61.2768 assertions/s.

  1) Failure:
test_notify_send(TestFreeBSD) [/usr/home/paul/develop/ruby/autotest-notification/lib/autotest_notification/linux.rb:35]:
unexpected invocation: AutotestNotification::FreeBSD.system('notify-send -h int:transient:1 -t 3000 -i image -u normal 'title' 'msg'')


  2) Failure:
test_notify_when_use_kdialog_with_speak(TestFreeBSD) [/usr/home/paul/develop/ruby/autotest-notification/lib/autotest_notification/freebsd.rb:12]:
unexpected invocation: AutotestNotification::FreeBSD.system('/usr/local/bin/espeak '1 test failed'')


  3) Failure:
test_notify_when_use_notify_with_speak(TestFreeBSD) [/usr/home/paul/develop/ruby/autotest-notification/lib/autotest_notification/freebsd.rb:12]:
unexpected invocation: AutotestNotification::FreeBSD.system('/usr/local/bin/espeak '1 test failed'')


  4) Failure:
test_notify_when_use_zenity_with_speak(TestFreeBSD) [/usr/home/paul/develop/ruby/autotest-notification/lib/autotest_notification/freebsd.rb:12]:
unexpected invocation: AutotestNotification::FreeBSD.system('/usr/local/bin/espeak '1 test failed'')


  5) Failure:
test_notify_send(TestLinux) [/usr/home/paul/develop/ruby/autotest-notification/lib/autotest_notification/linux.rb:35]:
unexpected invocation: AutotestNotification::Linux.system('notify-send -h int:transient:1 -t 3000 -i image -u normal 'title' 'msg'')
```

I'm new to test/unit & mocha (usually I do rspec) so I don't quite understand this "unexpected invocation" error.

**Comment by argent-smith** [comment]
However, the whole thing is working for me in live autotest.

**Comment by carlosbrando** [comment]
Hmm... I have the same error. The problem is that I'm without time to test it right now. Can you look the other tests and try to fix it? If you can't, I will check it on the weekend.

**Comment by argent-smith** [comment]
I could; I just need the idea what gives "unexpected invocation".

**Comment by argent-smith** [comment]
@carlosbrando I've found what to do! I'll do the thing and show you the PR ASAP!

**Pull request merged**
